global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "training_stats"
    scrape_interval: 3s
    scrape_timeout: 3s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["training:8001"]

  - job_name: "inference_stats"
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["inference-api:8000"]

  - job_name: "node"
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
