scrape_configs:
  - job_name: "training_stats"
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["training:8001"]

  - job_name: "inference_stats"
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["inference-api:8000"]
